// Scout — content collections
//
// Generated by astro-builder. Lives at src/content.config.ts
// (NEVER src/content/config.ts — that is the legacy Astro 2 location).
//
// Every collection follows one i18n contract:
//   - ONE collection per content type — never one per language.
//   - Locale subfolders: src/content/<type>/en/, etc.
//   - `lang` discriminates the entry's locale (enum of configured locales).
//   - `translationKey` links the same entry across locales.
//   - `tags: string[]` stays flexible — never a fixed category enum.
//   - `draft: true` keeps an entry out of listings, feeds, and sitemaps.
import { defineCollection, z } from "astro:content";
import { glob } from "astro/loaders";

// Single source of truth for the lang enum — mirror of astro.config.ts locales.
const locales = ["en"] as const;

// docs — the documentation reader (MDX). Sidebar-organized, ordered prose.
// `date` is intentionally absent: docs are reference, not a dated feed. A
// dated `blog` collection + RSS lands in phase 2.
const docs = defineCollection({
  loader: glob({ pattern: "**/*.{md,mdx}", base: "./src/content/docs" }),
  schema: z.object({
    title: z.string(),
    description: z.string(),
    sidebarLabel: z.string().optional(),
    order: z.number(),
    group: z.enum(["Getting started", "Core concepts", "Reference"]),
    tags: z.array(z.string()).default([]),
    translationKey: z.string(),
    lang: z.enum(locales),
    draft: z.boolean().default(false),
  }),
});

export const collections = { docs };
