// Scout — Astro configuration
//
// Generated by astro-builder. Lives at astro.config.ts
// (NEVER astro.config.mjs — this stack configures in TypeScript).
import mdx from "@astrojs/mdx";
import sitemap from "@astrojs/sitemap";
import { defineConfig } from "astro/config";

export default defineConfig({
  // Mandatory. Every absolute URL on the site — canonicals, hreflang
  // alternates, OG tags, RSS links, the sitemap — derives from this value.
  // Never hardcode the origin anywhere else.
  site: "https://scout.pcamarajr.dev",

  // Static output for Vercel static hosting — no SSR adapter needed. A future
  // client-side verdict-board fetch island stays static-compatible.
  output: "static",

  i18n: {
    defaultLocale: "en",
    locales: ["en"],
    // English-only v1 with NO URL prefix: pages live at the site root
    // (/, /docs/...), not under /en/. i18n stays latent for a future pt-BR —
    // adding a second locale later flips prefixDefaultLocale and reshapes the
    // routes. This deliberately overrides the plugin's prefixDefaultLocale: true
    // default because only English ships in v1.
    routing: { prefixDefaultLocale: false, redirectToDefaultLocale: false },
  },

  // Official Astro integrations only. @astrojs/sitemap emits
  // /sitemap-index.xml at build time; public/robots.txt points at it.
  // @astrojs/mdx powers the docs collection.
  integrations: [mdx(), sitemap()],
});
