// Scout — Astro configuration
//
// Generated by astro-builder. Lives at astro.config.ts
// (NEVER astro.config.mjs — this stack configures in TypeScript).
import mdx from "@astrojs/mdx";
import sitemap from "@astrojs/sitemap";
import { defineConfig } from "astro/config";

export default defineConfig({
  // Mandatory. Every absolute URL on the site — canonicals, hreflang
  // alternates, OG tags, RSS links, the sitemap — derives from this value.
  // Never hardcode the origin anywhere else.
  site: "https://scout.pcamarajr.dev",

  // Static output for Vercel static hosting — no SSR adapter needed. A future
  // client-side verdict-board fetch island stays static-compatible.
  output: "static",

  // The docs entry. /docs has no page of its own — the sidebar IS the docs
  // nav — so it redirects into the first reading page, where the vision is
  // reinforced first. Astro emits a static HTML redirect for this at build.
  redirects: {
    "/docs": "/docs/introduction/",
  },

  // Code blocks in docs prose ship dark, on-brand. Shiki's github-dark theme
  // matches the design's dark `.codeblock`; the reading column stays light
  // paper while code stands apart in a dark slab (DocPageView styles the frame).
  markdown: {
    shikiConfig: { theme: "github-dark" },
  },

  i18n: {
    defaultLocale: "en",
    locales: ["en"],
    // English-only v1 with NO URL prefix: pages live at the site root
    // (/, /docs/...), not under /en/. i18n stays latent for a future pt-BR —
    // adding a second locale later flips prefixDefaultLocale and reshapes the
    // routes. This deliberately overrides the plugin's prefixDefaultLocale: true
    // default because only English ships in v1.
    routing: { prefixDefaultLocale: false, redirectToDefaultLocale: false },
  },

  // Official Astro integrations only. @astrojs/sitemap emits
  // /sitemap-index.xml at build time; public/robots.txt points at it.
  // @astrojs/mdx powers the docs collection.
  integrations: [mdx(), sitemap()],
});
