// Scout — content collection queries
//
// Generated by astro-builder. Lives at src/lib/content.ts.
//
// ALL collection access goes through this module — page-views never call
// getCollection() directly. That keeps the site-wide query rules in exactly
// one place: filter by `lang`, exclude drafts, sort deterministically. A
// page-view asks "give me this locale's docs" and stays ignorant of how
// entries are stored or ordered.
import { getCollection } from "astro:content";

/**
 * Published docs for a locale, sorted by sidebar group then `order`.
 * Filtering inside getCollection() keeps draft exclusion next to the locale
 * filter so neither can be forgotten.
 */
export async function getDocsByLang(lang: string | undefined) {
  const entries = await getCollection(
    "docs",
    ({ data }) => data.lang === lang && !data.draft,
  );
  return entries.toSorted((a, b) => a.data.order - b.data.order);
}
