// Scout — locale-aware formatting
//
// Generated by astro-builder. Lives at src/lib/format.ts.
//
// All human-readable dates and numbers go through here, built on Intl —
// never a date/number library, never manual string assembly (month names,
// thousands separators, and digit grouping all differ per locale). Components
// pass `Astro.currentLocale` and a value; this module owns the presentation.
//
// Intl formatters are expensive to construct and a static build calls these
// once per entry per page, so each is memoized per locale.

const dateFormatters = new Map<string, Intl.DateTimeFormat>();
const numberFormatters = new Map<string, Intl.NumberFormat>();

/** Long-form date for bylines and listings: "March 12, 2026". */
export function formatDate(date: Date, locale: string | undefined): string {
  const resolved = locale ?? "en";
  let formatter = dateFormatters.get(resolved);
  if (!formatter) {
    formatter = new Intl.DateTimeFormat(resolved, { dateStyle: "long" });
    dateFormatters.set(resolved, formatter);
  }
  return formatter.format(date);
}

/** Plain number with locale grouping and decimals: "1,234.5". */
export function formatNumber(
  value: number,
  locale: string | undefined,
): string {
  const resolved = locale ?? "en";
  let formatter = numberFormatters.get(resolved);
  if (!formatter) {
    formatter = new Intl.NumberFormat(resolved);
    numberFormatters.set(resolved, formatter);
  }
  return formatter.format(value);
}
