// Scout — translator factory
//
// Generated by astro-builder. Lives at src/lib/i18n.ts.
//
// The one i18n deep module: every component calls
// `const tl = createTranslator(Astro.currentLocale)` and asks for keys —
// nothing else knows where strings live, how fallback works, or what the
// default locale is. Locale JSONs use FLAT dotted keys ("notFound.title"),
// which keeps lookup a plain property access and makes `MessageKey` a free
// compile-time union: a typo in a tl() call is a TypeScript error, not a
// blank string in production.
import defaultMessages from "../i18n/en.json";

/** Union of every key in the default locale file — the i18n contract. */
export type MessageKey = keyof typeof defaultMessages;

// Eagerly bundle every locale file. Adding a locale = adding one JSON file;
// this module never changes.
const messages = import.meta.glob<Record<string, string>>("../i18n/*.json", {
  eager: true,
  import: "default",
});

/**
 * Returns a `tl()` function bound to `locale` (pass `Astro.currentLocale`).
 *
 * Resolution order: requested locale → default locale → the key itself.
 * The last step means a missing translation degrades to visible debug text
 * instead of an empty element.
 */
export function createTranslator(
  locale: string | undefined,
): (key: MessageKey) => string {
  const table =
    (locale && messages[`../i18n/${locale}.json`]) || defaultMessages;
  return (key) =>
    (table as Record<string, string>)[key] ?? defaultMessages[key] ?? key;
}
