// Scout — URL builders
//
// Generated by astro-builder. Lives at src/lib/urls.ts.
//
// Every internal href on the site comes from this module — components never
// concatenate locale prefixes by hand.
//
// i18n NOTE (override): v1 is English-only with `prefixDefaultLocale: false`,
// so the default locale is UNPREFIXED — `/`, `/docs/intro/`. These builders
// therefore omit the prefix for the default locale and add it only for any
// future non-default locale (latent pt-BR). This is the single file that knows
// the prefixing rule. All builders return root-relative, trailing-slashed
// paths; absolute URLs (canonical, OG, feeds) are BaseLayout's job via
// `Astro.site`.

const DEFAULT_LOCALE = "en";

/** Path prefix for a locale: "" for the default (unprefixed) locale, "/<locale>" otherwise. */
function localePrefix(locale: string): string {
  return locale === DEFAULT_LOCALE ? "" : `/${locale}`;
}

/** Root-relative URL for any locale-aware path. The primitive every other builder uses. */
export function buildLocaleUrl(locale: string, ...segments: string[]): string {
  const tail = segments.length > 0 ? `${segments.join("/")}/` : "";
  return `${localePrefix(locale)}/${tail}`;
}

/** Homepage for a locale: `/` (default) or `/pt-BR/`. */
export function buildHomeUrl(locale: string): string {
  return buildLocaleUrl(locale);
}

/** RSS feed for a locale: `/rss.xml` (default). No trailing slash — it is a file, not a page. */
export function buildRssUrl(locale: string): string {
  return `${localePrefix(locale)}/rss.xml`;
}

// ── Content-type builders ───────────────────────────────────────────────────
//
// One builder per content collection, delegating to buildLocaleUrl. Entry ids
// from glob() loaders include the locale folder ("en/intro") — strip it; the
// URL prefix (when present) carries the locale.

/** Docs entry: `/docs/intro/`. */
export function buildDocUrl(slug: string, locale: string): string {
  return buildLocaleUrl(locale, "docs", slug.replace(`${locale}/`, ""));
}
